import { Metadata } from "next";
import SchemaMarkup from "@/components/seo/SchemaMarkup";
import BreadcrumbSchema from "@/components/seo/BreadcrumbSchema";

export const metadata: Metadata = {
  title: "Disclaimer | ClearNest",
  description: "Legal disclaimer and terms of use for the ClearNest mortgage calculator website.",
  alternates: { canonical: "https://clearnestcalculator.site/disclaimer" },
};

export default function DisclaimerPage() {
  const schema = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "name": "ClearNest Disclaimer",
    "url": "https://clearnestcalculator.site/disclaimer"
  };

  const breadcrumbs = [
    { name: "Home", url: "https://clearnestcalculator.site" },
    { name: "Disclaimer", url: "https://clearnestcalculator.site/disclaimer" }
  ];

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <SchemaMarkup schema={schema} />
      <BreadcrumbSchema items={breadcrumbs} />
      
      <div className="mb-12">
        <h1 className="text-4xl font-bold text-text-primary mb-4">Disclaimer</h1>
        <p className="text-text-muted">Last Updated: March 15, 2026</p>
      </div>

      <div className="prose prose-lg max-w-none text-text-primary">
        <p>
          The information and calculators provided on ClearNest (the "Website") are for educational and informational purposes only. By using this Website, you agree to the terms outlined in this disclaimer.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Not Financial Advice</h2>
        <p>
          ClearNest is not a licensed mortgage lender, broker, financial advisor, or tax professional. The content and tools on this Website do not constitute professional financial, legal, or tax advice. You should consult with a qualified professional before making any financial decisions, including applying for a mortgage or purchasing a home.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Estimates Only</h2>
        <p>
          The results generated by our calculators are estimates based on the information you input and standard industry formulas. They are designed to give you a general idea of potential costs and scenarios. 
        </p>
        <p>
          <strong>These estimates are not a guarantee of loan approval or specific loan terms.</strong> Your actual interest rate, monthly payment, closing costs, and loan terms will be determined by a lender based on a comprehensive review of your credit history, income, debt, and the specific property you intend to purchase.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Variables and Assumptions</h2>
        <p>
          Our calculators make certain assumptions to provide estimates, which may not reflect your exact situation. For example:
        </p>
        <ul className="list-disc pl-6 mb-6">
          <li>Property taxes and home insurance rates vary significantly by location and property type. The default values provided are national averages and should be adjusted to reflect your specific area.</li>
          <li>Private Mortgage Insurance (PMI) rates vary based on your credit score, down payment, and lender.</li>
          <li>HOA fees are highly variable and are not applicable to all properties.</li>
          <li>Calculations assume payments are made on time and in full every month.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">No Liability</h2>
        <p>
          ClearNest makes no warranties, expressed or implied, regarding the accuracy, completeness, or reliability of the calculators or information provided on this Website. We shall not be held liable for any errors, omissions, or any losses, injuries, or damages arising from the use of this Website or reliance on its content.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">External Links</h2>
        <p>
          This Website may contain links to external websites that are not provided or maintained by or in any way affiliated with ClearNest. Please note that we do not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.
        </p>
      </div>
    </div>
  );
}
